---
- name: AWS
  hosts: all
  tasks:
      - name: ping pong
        ping:
      - name: Upgrade currently installed packages
        apt: "upgrade=dist state=present update_cache=true cache_valid_time=600"
      - name: Install useful packages
        apt: "name={{ item }} state=present"
        with_items:
           - curl
           - telnet
           - wget
           - tmux
           - python-setuptools

      - name: Install PIP 
        command: easy_install pip 

      - name: Install Docker keys
        apt_key: state=present keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9
      - name: Install Docker repository
        apt_repository: repo='deb https://get.docker.io/ubuntu docker main' state=present
      - name: Install Docker
        apt: name=lxc-docker state=latest update_cache=true cache_valid_time=600
      - name: Add ubuntu to the docker group
        user: name=ubuntu state=present groups=docker
#     - name: Have Docker use Consul for DNS
#       lineinfile: dest=/etc/default/docker line='DOCKER_OPTS="--dns 192.168.44.60 --dns 8.8.8.8 --dns 8.8.4.4 --dns-search service.consul"'
      - name: Set Memory and Swap Accounting
        lineinfile: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX=""' line='GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
      - name: Rebuild GRUB
        command: update-grub
      - name: Restart Docker
        service: name=docker state=restarted
      - name: Install Docker Compose
        pip: name=docker-compose extra_args='--upgrade'

